{% set name = "trame-tauri" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-tauri-{{ version }}.tar.gz
  sha256: 2643bbdfa3cf06438463c2814e43f325182c4f164c7f19fbaa57b7b9fd57ee99

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - trame-client

test:
  imports:
    - trame
    - trame_tauri
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kitware/trame-tauri
  summary: Helper widget to provide simpler integration with Tauri
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jourdain
    - psavery
