{% set name = "trame-tauri" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-tauri-{{ version }}.tar.gz
  sha256: 44e66fccd7e8df6be3ceb1e9b25f6874a0cffc2af450c517568898b808be5981

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - trame-client

test:
  imports:
    - trame
    - trame_tauri
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kitware/trame-tauri
  summary: Helper widget to provide simpler integration with Tauri
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jourdain
    - psavery
